import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Calories {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()

  //For the sake of simplicity, a Todo has only a name.
  final DateTime day;
  final double calories;
  //Default constructor
  Calories(this.day, this.calories);
  //Todo
}

@entity
class Steps {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()

  //For the sake of simplicity, a Todo has only a name.
  final DateTime day;
  final double steps;

  //Default constructor
  Steps(this.day, this.steps);
  //Todo
}

@entity
class Distance {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey()

  //For the sake of simplicity, a Todo has only a name.
  final DateTime day;
  final double distance;
  //Default constructor
  Distance(this.day, this.distance);
  //Todo
}
